### ISSUE TITLE
Same node version for Dockerfiles

### ISSUE THREAD

**Issue by KuhArt** [paralect/ship#18]
Maybe we need some consistency in node version for web/api/landing Dockerfiles
https://github.com/paralect/ship/blob/master/api/Dockerfile.dev#L1
https://github.com/paralect/ship/blob/master/landing/Dockerfile#L1
https://github.com/paralect/ship/blob/master/web/Dockerfile#L1

**Comment by ezhivitsa** [comment]
Node.js versions was updated.
