### ISSUE TITLE
_id or not id ?

### ISSUE THREAD

**Issue by clabnet** [paralect/ship#197]
Hi, 
for some reasons I need to change the `_id` field name with `id`. 
I have this code : 
```
export function swapId(obj) {
  if (obj.id) {
    obj._id = obj.id;
    delete obj.id;
  } else if (obj._id) {
    obj.id = obj._id;
    delete obj._id;
  }
  return obj
}
```
Can I add this code on centralized location where all update calls and all create calls passing ?
If yes, where I should be add this ? Is there another mode ?

Thanks in advance.

**Comment by fruneen** [comment]
Hi there,

Thank you for reaching out with your request. Altering the `_id` field name could indeed be a sensitive operation, especially considering its usage across your package and unit tests. Here's a suggestion on how you can approach this:

You can leverage the provided `CustomService` and `createService` functions to handle your CRUD operations in a more controlled manner. Here's a basic example of how you could utilize it:

```javascript
import { Database, Service, ServiceOptions, IDocument } from '@paralect/node-mongo';
import config from 'config';

const database = new Database(config.MONGO_URI, config.MONGO_DB_NAME);

class CustomService<T extends IDocument> extends Service<T> {
  // You can add new methods or override existing ones here
}

function createService<T extends IDocument>(collectionName: string, options: ServiceOptions = {}) {
  return new CustomService<T>(collectionName, database, options);
}

export default Object.assign(database, {
  createService,
});
```

By using this approach, you can seamlessly integrate custom logic into your database operations without directly modifying the `_id` field name. Additionally, it provides a structured way to handle CRUD operations across the app
