### ISSUE TITLE
Can Railway.app be added to the list of where we can deploy?

### ISSUE THREAD

**Issue by arguemore** [paralect/ship#291]

**Comment by fruneen** [comment]
Hey! 👋 

Thanks for the suggestion!

The task has been added to the project board - https://github.com/orgs/paralect/projects/1/views/1?pane=issue&itemId=58247906

**Comment by fruneen** [comment]
I took a look at Railway again and, unfortunately, Railway doesn't provide necessary functionality for deploying ship.
Railway doesn't have a job before deploy (for migrator running) and monorepo deployment using Dockerfiles.

So, I'm closing this question as irrelevant at the moment.

**Comment by arguemore** [comment]
Hey there. Thanks for looking into it! Best wishes to Paralect
