### ISSUE TITLE
Do we need query validate in the base.validator.js?

### ISSUE THREAD

**Issue by Ivanko5417** [paralect/ship#30]

**Comment by anorsich** [comment]
@Ivanko5417 Could you give us some example of what do you mean? That would help us a lot!

**Comment by Ivanko5417** [comment]
@anorsich Now, ctx.query and ctx.params (besides GET request) aren't validating by base.validator. I think something like that will be better:
`if (ctx.method !== 'GET') {
      body = ctx.request.body;
    }

    joiResult = Joi.validate({ ...body, ...ctx.query, ...ctx.params }, joiSchema, joiOptions);`
(base.validator.js 52-56-rows

**Comment by Ivanko5417** [comment]
:cry:
