### ISSUE TITLE
Error after ask for "Forgot Password?"

### ISSUE THREAD

**Issue by AliaksandrHudnyi** [paralect/ship#32]
1) Open http://ship-demo.paralect.com/signin
2) Press "Forgot Password?"
3) Enter your Valid email
Issue: An unexpected error has occurred. https://i.imgur.com/c5K2yVU.png

**Comment by ezhivitsa** [comment]
@AliaksandrHudnyi Fixed.

**Comment by AliaksandrHudnyi** [comment]
@ezhivitsa Fixed. Email Sent page now opens, but email haven't sent. 
I added this issue as seperate task https://github.com/paralect/ship/issues/36
Thanks
