### ISSUE TITLE
Hot reloading arrow functions on classes do not bind `this`

### ISSUE THREAD

**Issue by Ivanko5417** [paralect/ship#38]
The same issue: https://github.com/gaearon/react-hot-loader/issues/787
I think, we have to update react-hot-loader to version 4.0.0

**Comment by ezhivitsa** [comment]
@Ivanko5417 Can you reproduce this bug in the repository `paralect/koa-react-starter`? I can't reproduce this bug. Also we already use `react-hot-loader` of the version 4.0.0.

**Comment by Ivanko5417** [comment]
@ezhivitsa looks good. Sorry, I'm using the old version ship with `react-hot-loader` with a different version.
