### ISSUE TITLE
Implement merge process of stack components into the ship

### ISSUE THREAD

**Issue by anorsich** [paralect/ship#7]
[Stack-merge](https://github.com/startupsummer/stack-merge) repository is private at the moment. Will make it public after the first release. 
Basically, we need few things:
1. Merge components into the ship, so it easy to release new versions of Ship after any of the components change. Ideally, the process should create PR, which can be reviewed, but we can start with a simpler version. 
2. Update list of components which form current version of the Ship as described in #5. 
3. Write a readme in the [Stack Merge](https://github.com/startupsummer/stack-merge) repository with detailed steps of how to produce new versions of Ship.

**Comment by anorsich** [comment]
@ezhivitsa I think we can close this issue. Do you mind reviewing others as well?

**Comment by ezhivitsa** [comment]
@anorsich Items 2 and 3 are not finished yet;)
