### ISSUE TITLE
Implement main page of landing website for the Ship

### ISSUE THREAD

**Issue by anorsich** [paralect/ship#8]
[The repository](https://github.com/startupsummer/ship-site) is private at the moment. Obviously, it should be based on our own [next.js based template](https://github.com/paralect/nextjs-landing-starter)

1. The page should include a description of what Ship does, list of products, which already use any of the components or based on Ship. 
2. Deploy a page to the /ship at paralect.com website. 
3. Include a list of all current components alongside with links to the GitHub. 
4. Make sure the page is responsive and works well on mobile/web/tablets.

**Comment by danilyanich** [comment]
@anorsich Check the page!
Also maybe we can close the issue, if page is ready?

**Comment by anorsich** [comment]
@danilyanich Let's review this page and wizard together first, but It looks like we're very close to closing this issue!

**Comment by anorsich** [comment]
@danilyanich I think we can close this issue after you do the latest set of changes we've discussed earlier. I've already included a link to the website in the readme, yauuu!

**Comment by anorsich** [comment]
@danilyanich I think we can finally close this issue, as well as V1 :) Thank you for a great job!
